# https://docs.astral.sh/ruff/
name: Ruff linter
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ruff-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install .[dev]
      - name: Ruff Check
        run: ruff check .
